### ISSUE TITLE
[docs] Comparison to AWS SSO

### ISSUE THREAD

**Issue by aidansteele** [iamarkadyt/aws-auth#4]
It would be useful to have a comparison to using [AWS SSO](https://aws.amazon.com/single-sign-on/) in the readme. It's _somewhat_ covered in the "project goals" section, but the comparison is only to:

* No MFA on IAM users (bad, as the readme says)
* Expensive third-party SSO (complex and expensive)

AWS SSO is first-party SSO with MFA support and is free, so the comparison is probably different? E.g. SDK compatibility, environment support, etc. (Sorry I don't have specifics, I only just read the readme and had this question!)

**Comment by iamarkadyt** [comment]
@aidansteele I've added a comparison to the FAQ section! :+1:
