### ISSUE TITLE
M1 support

### ISSUE THREAD

**Issue by saasseckin** [iamarkadyt/aws-auth#5]
Hello, 

Any plans to add apple m1 support?

**Comment by iamarkadyt** [comment]
@saasseckin hmm, I don't use a mac. What needs to be done for that?

**Comment by danbee** [comment]
@iamarkadyt Absolutely nothing from what I can tell. It's up to the user to install an M1 compatible version of node.

**Comment by iamarkadyt** [comment]
That's what I thought too. We're too high up the software stack for this. @saasseckin let me know if you want to reopen this.
